{% set name = "libxmlplusplus" %}
{% set version = "5.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/libxmlplusplus/libxmlplusplus/releases/download/{{ version }}/libxml++-{{ version }}.tar.xz
  sha256: 7c17cc3e5a2214314dee5a1354f4b436f266ded6185232a0534f352a76240d5a

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - meson
    - pkg-config
    - ninja
    - {{ compiler('cxx') }}
  host:
    - libxml2
    - glib
    - glibmm
  run:
    - libxml2
    - glib
    - glibmm

test:
  commands:
    - test -f ${PREFIX}/lib/libxml++-3.0.so  # [linux]
    - test -f ${PREFIX}/lib/libxml++-3.0.dylib  # [osx]

about:
  home: https://libxmlplusplus.github.io/libxmlplusplus/
  license: LGPL-2.1-only
  license_family: GPL2
  license_file: COPYING
  summary: This library provides a C++ interface to XML files. It uses libxml2 to access the XML files.

extra:
  recipe-maintainers:
    - izahn
