schema_version: 1

context:
  version: "5.6.1"

package:
  name: libxmlplusplus
  version: ${{ version }}

source:
  url: https://github.com/libxmlplusplus/libxmlplusplus/releases/download/${{ version }}/libxml++-${{ version }}.tar.xz
  sha256: 4996e8a73995e8a4cd656c8591dce38181146edfc30cb47c97d1db3c56990ad7

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - meson
    - ninja
    - pkg-config
  host:
    - libxml2-devel
  run_exports:
    - ${{ pin_subpackage('libxmlplusplus', upper_bound='x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libxml++-5.0${SHLIB_EXT}

about:
  license: LGPL-2.1-only
  license_file: COPYING
  summary: This library provides a C++ interface to XML files. It uses libxml2 to access the XML files.
  homepage: https://libxmlplusplus.github.io/libxmlplusplus/

extra:
  recipe-maintainers:
    - izahn
